version: "3"

services:

  discovery:
    build:
      context: ./
      dockerfile: ./discovery/Dockerfile
    expose:
    - 8001
    networks:
    - xds-testing

  envoy:
    depends_on:
    - discovery
    image: envoyproxy/envoy:latest
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -l error --component-log-level config:debug -c /etc/envoy/envoy.yaml
    expose:
    - 9901
    - 10000
    ports:
    - 9901:9901
    - 10000:10000
    networks:
    - xds-testing

networks:
  xds-testing:
